name: cell
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip>=19.0.3
  - matplotlib>=3.1.2
  - opencv>=4.1
  - pytorch>=1.3.1
  - scikit-image>=0.16.2
  - scipy>=1.3.2
  - torchvision>=0.5.0
  - cudatoolkit=10.2
  - cuda100
  - pip
  - imagecodecs
  - filterpy
  - tensorflow-gpu
  - tqdm
  - imgaug
  - connected-components-3d
